# Generated by Django 2.1.5 on 2022-04-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20220404_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='addMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(max_length=100)),
                ('medicineuse', models.CharField(max_length=100)),
            ],
        ),
    ]
